name: 'zuora'
version: '0.3.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
profile: 'zuora'
vars:
  zuora: 
    account: "{{ source('zuora_source', 'stg_zuora__account') }}"
    amendment: "{{ source('zuora_source', 'stg_zuora__amendment') }}"
    contact: "{{ source('zuora_source', 'stg_zuora__contact') }}"
    credit_balance_adjustment: "{{ source('zuora_source', 'stg_zuora__credit_balance_adjustment') }}"
    invoice: "{{ source('zuora_source', 'stg_zuora__invoice') }}"
    invoice_item: "{{ source('zuora_source', 'stg_zuora__invoice_item') }}"
    invoice_payment: "{{ source('zuora_source', 'stg_zuora__invoice_payment') }}"
    order: "{{ source('zuora_source', 'stg_zuora__order') }}"
    payment: "{{ source('zuora_source', 'stg_zuora__payment') }}"
    payment_method: "{{ source('zuora_source', 'stg_zuora__payment_method') }}"
    product_rate_plan_charge: "{{ source('zuora_source', 'stg_zuora__product_rate_plan_charge') }}"
    product_rate_plan: "{{ source('zuora_source', 'stg_zuora__product_rate_plan') }}"
    product: "{{ source('zuora_source', 'stg_zuora__product') }}"
    rate_plan_charge: "{{ source('zuora_source', 'stg_zuora__rate_plan_charge') }}"
    rate_plan: "{{ source('zuora_source', 'stg_zuora__rate_plan') }}"
    refund: "{{ source('zuora_source', 'stg_zuora__refund') }}"
    refund_invoice_payment: "{{ source('zuora_source', 'stg_zuora__refund_invoice_payment') }}"
    subscription: "{{ source('zuora_source', 'stg_zuora__subscription') }}"
    taxation_item: "{{ source('zuora_source', 'stg_zuora__taxation_item') }}"

  zuora_account_pass_through_columns: []
  zuora_rate_plan_pass_through_columns: []
  zuora_rate_plan_charge_pass_through_columns: []
  zuora_subscription_pass_through_columns: []

models:
  zuora:
    +schema: zuora_dbt  # Change to new schema
    +materialized: table
