name: 'zuora'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  zuora: 
    account: "{{ ref('stg_zuora__account') }}"
    accounting_code: "{{ ref('stg_zuora__accounting_code') }}"
    amendment: "{{ ref('stg_zuora__amendment') }}"
    contact: "{{ ref('stg_zuora__contact') }}"
    credit_balance_adjustment: "{{ ref('stg_zuora__credit_balance_adjustment') }}"
    invoice_item: "{{ ref('stg_zuora__invoice_item') }}"
    invoice: "{{ ref('stg_zuora__invoice') }}"
    journal_entry_item: "{{ ref('stg_zuora__journal_entry_item') }}"
    journal_entry: "{{ ref('stg_zuora__journal_entry') }}"
    order_item: "{{ ref('stg_zuora__order_item') }}"
    order: "{{ ref('stg_zuora__order') }}"
    payment_method: "{{ ref('stg_zuora__payment_method') }}"
    payment: "{{ ref('stg_zuora__payment') }}"
    product_rate_plan_charge: "{{ ref('stg_zuora__product_rate_plan_charge') }}"
    product_rate_plan: "{{ ref('stg_zuora__product_rate_plan') }}"
    product: "{{ ref('stg_zuora__product') }}"
    rate_plan_charge: "{{ ref('stg_zuora__rate_plan_charge') }}"
    rate_plan: "{{ ref('stg_zuora__rate_plan') }}"
    refund: "{{ ref('stg_zuora__refund') }}"
    subscription: "{{ ref('stg_zuora__subscription') }}"
    taxation_item: "{{ ref('stg_zuora__taxation_item') }}"

  zuora_account_pass_through_columns: []
  zuora_rate_plan_pass_through_columns: []
  zuora_rate_plan_charge_pass_through_columns: []
  zuora_subscription_pass_through_columns: []

models:
  zuora:
    +schema: zuora
    +materialized: table
    intermediate:
      +schema: zuora_int
      +materialized: table

  
